BEGIN;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Library issue", "chip": "education"}'::jsonb, true) WHERE id = 12;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Classmate issue", "chip": "education"}'::jsonb, true) WHERE id = 13;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Group issue", "chip": "work"}'::jsonb, true) WHERE id = 14;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "City cinema issue", "chip": "entertainment"}'::jsonb, true) WHERE id = 15;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Co-working hub issue", "chip": "work"}'::jsonb, true) WHERE id = 16;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Wellness program", "chip": "work"}'::jsonb, true) WHERE id = 17;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Library issue", "chip": "education"}'::jsonb, true) WHERE id = 18;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Green Campus Initiative", "chip": "environment"}'::jsonb, true) WHERE id = 19;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Safety improvements", "chip": "community"}'::jsonb, true) WHERE id = 20;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "School Council", "chip": "education"}'::jsonb, true) WHERE id = 21;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Environmental Club Committee", "chip": "environment"}'::jsonb, true) WHERE id = 22;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Town Planning Committee", "chip": "sports"}'::jsonb, true) WHERE id = 23;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "School administration", "chip": "education"}'::jsonb, true) WHERE id = 24;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "The issue", "chip": ""}'::jsonb, true) WHERE id = 25;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Bookstore issue", "chip": "entertainment"}'::jsonb, true) WHERE id = 26;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Your manager", "chip": ""}'::jsonb, true) WHERE id = 27;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Cinema management", "chip": "entertainment"}'::jsonb, true) WHERE id = 28;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "This club issue", "chip": "sports"}'::jsonb, true) WHERE id = 29;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Restaurant issue", "chip": "food"}'::jsonb, true) WHERE id = 30;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Platform development", "chip": "education"}'::jsonb, true) WHERE id = 31;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Changes", "chip": "transport"}'::jsonb, true) WHERE id = 32;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Cleaning service", "chip": "community"}'::jsonb, true) WHERE id = 33;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Building Management Committee", "chip": "community"}'::jsonb, true) WHERE id = 34;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Changes", "chip": "education"}'::jsonb, true) WHERE id = 35;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Car rental", "chip": "travel"}'::jsonb, true) WHERE id = 36;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Mall management", "chip": ""}'::jsonb, true) WHERE id = 37;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Parks Department", "chip": "community"}'::jsonb, true) WHERE id = 38;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Course coordinator", "chip": "education"}'::jsonb, true) WHERE id = 39;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Volunteer coordinator", "chip": "community"}'::jsonb, true) WHERE id = 40;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Hotel manager", "chip": "travel"}'::jsonb, true) WHERE id = 41;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "School director", "chip": "education"}'::jsonb, true) WHERE id = 42;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Tutoring service", "chip": ""}'::jsonb, true) WHERE id = 43;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Pharmacy issue", "chip": "health"}'::jsonb, true) WHERE id = 44;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Festival organizers", "chip": "culture"}'::jsonb, true) WHERE id = 45;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Mobile provider", "chip": "technology"}'::jsonb, true) WHERE id = 46;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Museum management", "chip": "culture"}'::jsonb, true) WHERE id = 47;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Streaming service", "chip": "entertainment"}'::jsonb, true) WHERE id = 48;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Book club", "chip": ""}'::jsonb, true) WHERE id = 49;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Arena management", "chip": "entertainment"}'::jsonb, true) WHERE id = 50;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Airline issue", "chip": "travel"}'::jsonb, true) WHERE id = 51;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Internet service", "chip": "technology"}'::jsonb, true) WHERE id = 52;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Grooming salon", "chip": ""}'::jsonb, true) WHERE id = 53;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Food delivery", "chip": "food"}'::jsonb, true) WHERE id = 54;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Coworking space", "chip": ""}'::jsonb, true) WHERE id = 55;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Art gallery", "chip": "entertainment"}'::jsonb, true) WHERE id = 56;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Car manufacturer", "chip": ""}'::jsonb, true) WHERE id = 57;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Dental clinic", "chip": "health"}'::jsonb, true) WHERE id = 58;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Venue management", "chip": "entertainment"}'::jsonb, true) WHERE id = 59;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Photography academy", "chip": "entertainment"}'::jsonb, true) WHERE id = 60;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Yoga studio", "chip": "sports"}'::jsonb, true) WHERE id = 61;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Swimming center", "chip": "sports"}'::jsonb, true) WHERE id = 62;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Bicycle rental", "chip": "transport"}'::jsonb, true) WHERE id = 63;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Online store", "chip": ""}'::jsonb, true) WHERE id = 64;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Coffee subscription", "chip": "food"}'::jsonb, true) WHERE id = 65;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Escape room", "chip": "entertainment"}'::jsonb, true) WHERE id = 66;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Farmers market", "chip": "food"}'::jsonb, true) WHERE id = 67;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Cooking school", "chip": "food"}'::jsonb, true) WHERE id = 68;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Security company", "chip": "safety"}'::jsonb, true) WHERE id = 69;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Language exchange", "chip": "culture"}'::jsonb, true) WHERE id = 70;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Pet grooming", "chip": ""}'::jsonb, true) WHERE id = 71;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Furniture store", "chip": "housing"}'::jsonb, true) WHERE id = 72;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Music streaming", "chip": "entertainment"}'::jsonb, true) WHERE id = 73;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Photography studio", "chip": "entertainment"}'::jsonb, true) WHERE id = 74;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Travel agency", "chip": "travel"}'::jsonb, true) WHERE id = 75;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Meal delivery", "chip": "food"}'::jsonb, true) WHERE id = 76;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Car wash", "chip": ""}'::jsonb, true) WHERE id = 77;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Online tutoring", "chip": "education"}'::jsonb, true) WHERE id = 78;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Flower delivery", "chip": ""}'::jsonb, true) WHERE id = 79;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Smart device", "chip": "technology"}'::jsonb, true) WHERE id = 80;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Dental clinic", "chip": "health"}'::jsonb, true) WHERE id = 81;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Cinema management", "chip": "entertainment"}'::jsonb, true) WHERE id = 82;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Laundry service", "chip": ""}'::jsonb, true) WHERE id = 83;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Sports club", "chip": "sports"}'::jsonb, true) WHERE id = 84;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Bookstore issue", "chip": "entertainment"}'::jsonb, true) WHERE id = 85;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Parking app", "chip": "technology"}'::jsonb, true) WHERE id = 86;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Beauty salon", "chip": ""}'::jsonb, true) WHERE id = 87;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Grocery delivery", "chip": "food"}'::jsonb, true) WHERE id = 88;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Coworking space", "chip": ""}'::jsonb, true) WHERE id = 89;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Podcast platform", "chip": "entertainment"}'::jsonb, true) WHERE id = 90;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Pet grooming", "chip": ""}'::jsonb, true) WHERE id = 91;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Furniture store", "chip": "housing"}'::jsonb, true) WHERE id = 92;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Language learning", "chip": "culture"}'::jsonb, true) WHERE id = 93;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Bike rental", "chip": "travel"}'::jsonb, true) WHERE id = 94;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Online tutoring", "chip": "education"}'::jsonb, true) WHERE id = 95;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Car wash", "chip": ""}'::jsonb, true) WHERE id = 96;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Photography studio", "chip": "entertainment"}'::jsonb, true) WHERE id = 97;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Meal kit", "chip": "food"}'::jsonb, true) WHERE id = 98;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Escape room", "chip": "entertainment"}'::jsonb, true) WHERE id = 99;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Music streaming", "chip": "entertainment"}'::jsonb, true) WHERE id = 100;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Yoga studio", "chip": "sports"}'::jsonb, true) WHERE id = 101;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Travel agency", "chip": "travel"}'::jsonb, true) WHERE id = 102;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Craft brewery", "chip": "food"}'::jsonb, true) WHERE id = 103;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Interior design", "chip": "culture"}'::jsonb, true) WHERE id = 104;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Smart home", "chip": "technology"}'::jsonb, true) WHERE id = 105;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Subscription box", "chip": ""}'::jsonb, true) WHERE id = 106;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Volunteering organization", "chip": "community"}'::jsonb, true) WHERE id = 107;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Adventure park", "chip": "travel"}'::jsonb, true) WHERE id = 108;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Retirement planning", "chip": "money"}'::jsonb, true) WHERE id = 109;
UPDATE mock_tests SET mock_data = jsonb_set(mock_data, '{part1}', '{"topic": "Library committee", "chip": "education"}'::jsonb, true) WHERE id = 110;
COMMIT;