export type CatalogCategory = { cat: string; topics: string[] };
export const TOPIC_CATALOG: { grammar: CatalogCategory[]; vocabulary: CatalogCategory[] } = {
  grammar: [
    { cat: 'Tenses — present', topics: ['Present simple','Present continuous','Present simple vs continuous','Stative verbs','Verbs not used in continuous','Adverbs of frequency placement','Time expressions with present','Present in narratives'] },
    { cat: 'Tenses — past', topics: ['Past simple','Past continuous','Past simple vs past continuous','Past habits with used to','Past habits with would','Past time expressions','Sequencing past events','Stories in past tense'] },
    { cat: 'Tenses — perfect', topics: ['Present perfect simple','Present perfect continuous','Present perfect vs past simple','Present perfect with for / since','Present perfect with just / already / yet','Past perfect simple','Past perfect continuous','Past perfect vs past simple','Future perfect simple','Future perfect continuous'] },
    { cat: 'Tenses — future', topics: ['Will for predictions','Going to for plans','Will vs going to','Present continuous for arrangements','Present simple for timetables','Future continuous','Be about to','Be on the verge of','Future in time clauses'] },
    { cat: 'Modals — obligation & advice', topics: ['Must vs have to','Mustn\'t vs don\'t have to','Should / ought to / had better','Need to / needn\'t','Be supposed to','Modals for rules and laws','Strong vs weak obligation'] },
    { cat: 'Modals — ability & permission', topics: ['Can / could for ability','Be able to','Can / could / may for permission','Could vs was able to','Polite requests with would / could','Asking permission politely'] },
    { cat: 'Modals — possibility & deduction', topics: ['May / might / could for possibility','Must / can\'t / might for deduction','Past modals (must have / could have)','Should have / ought to have','Modals for hypothetical past','Modal + perfect infinitive','Degrees of certainty'] },
    { cat: 'Conditionals', topics: ['Zero conditional','First conditional','Second conditional','Third conditional','Mixed conditionals','Wishes & regrets (wish / if only)','Conditional connectors (unless / provided)','Inversion in conditionals','In case / as long as'] },
    { cat: 'Passive voice', topics: ['Passive — present tenses','Passive — past tenses','Passive — perfect tenses','Passive with modals','Passive with two objects','Impersonal passive (it is said that…)','Get-passive','Have / get something done (causative)'] },
    { cat: 'Reported speech', topics: ['Reporting statements','Tense changes (backshift)','Reporting questions','Reporting yes/no questions','Reporting commands & requests','Reporting verbs (suggest / accuse / deny)','Time & place changes','Reporting without backshift','Modal verbs in reported speech'] },
    { cat: 'Articles', topics: ['A vs an','The (specific reference)','Zero article (general statements)','Articles with names of places','Articles with countable / uncountable','Generic the (the rich / the elderly)','Articles in titles & headlines'] },
    { cat: 'Determiners & quantifiers', topics: ['Some / any','Much / many','A few / a little / few / little','Each / every / all','Both / either / neither','This / that / these / those','No / none','Enough / too','Whole / entire / all'] },
    { cat: 'Prepositions of time', topics: ['At / on / in for time','For / since / during','By / until / from-to','Time prepositions in narratives','Prepositions with parts of the day','Common time preposition mistakes'] },
    { cat: 'Prepositions of place & movement', topics: ['At / on / in for place','Above / below / beside / between','Across / through / along','Into / out of / onto / off','To / from / towards','Inside / outside','Around / round','In vs into (movement vs static)'] },
    { cat: 'Dependent prepositions', topics: ['Verbs + preposition (depend on, listen to)','Adjectives + preposition (good at, afraid of)','Nouns + preposition (reason for, solution to)','Different prepositions, different meaning','Common preposition mistakes','Phrasal verbs with two prepositions'] },
    { cat: 'Adjectives', topics: ['Adjective order','Comparative adjectives','Superlative adjectives','As ... as comparisons','Strong adjectives (boiling, freezing)','-ed vs -ing adjectives','Compound adjectives','Adjectives ending in -ly (friendly, lonely)','Order of adjectives with absolutes'] },
    { cat: 'Adverbs', topics: ['Adverbs of frequency','Adverbs of manner','Adverbs of degree','Adverbs of time','Position of adverbs in sentences','Adverb formation (-ly)','Adverbs vs adjectives (hard, fast, late)','Comparative & superlative adverbs','Sentence adverbs (luckily, frankly)'] },
    { cat: 'Connectors & linkers', topics: ['Coordinating conjunctions (and / but / or)','Subordinating conjunctions','Linkers of contrast (however / nevertheless)','Linkers of addition (moreover / furthermore)','Linkers of result (therefore / consequently)','Linkers of cause (because of / due to)','Linkers of purpose (so that / in order to)','Time linkers (while / as soon as / by the time)','Despite / in spite of','Whereas / while for contrast'] },
    { cat: 'Cleft sentences', topics: ['It-cleft sentences','What-cleft sentences','All-cleft sentences','Pseudo-cleft','Reverse cleft','The reason ... is that'] },
    { cat: 'Inversion', topics: ['Inversion after negative adverbials','Inversion with hardly / scarcely / no sooner','Inversion with not only ... but also','Inversion in conditionals','Inversion after so / such','Stylistic inversion'] },
    { cat: 'Subjunctive & advanced', topics: ['Subjunctive after suggest / insist / demand','Subjunctive after wish / if only','It\'s high time / it\'s about time','Were to + infinitive','Should + bare infinitive','Lest + subjunctive'] },
    { cat: 'Participle clauses', topics: ['Participle clauses (active)','Participle clauses (passive)','Reduced relative clauses','Participle as modifier','Dangling participles','Perfect participle (having done)'] },
    { cat: 'Verb + gerund / infinitive', topics: ['Verbs + gerund (enjoy, avoid, mind)','Verbs + infinitive (decide, want, hope)','Verbs with both — same meaning','Verbs with both — different meaning (remember / stop / try)','Verb + object + infinitive','Bare infinitive (after make / let / help)','To + gerund (look forward to, used to)','Help / dare / need patterns'] },
    { cat: 'Relative clauses', topics: ['Defining relative clauses','Non-defining relative clauses','Relative pronouns (who / which / that)','Whose / where / when','Relative clauses with prepositions','Quantifiers + of which / of whom','Omission of relative pronouns'] },
    { cat: 'Questions', topics: ['Yes/no questions','Wh-questions','Subject vs object questions','Question tags','Indirect questions','Negative questions','Question word + ever (whoever, whatever)','How + adjective questions'] },
    { cat: 'Phrasal verbs (grammar)', topics: ['Separable phrasal verbs','Inseparable phrasal verbs','Three-part phrasal verbs','Object position rules','Phrasal verbs in passive voice','Phrasal verbs vs prepositional verbs'] },
    { cat: 'Word formation', topics: ['Negative prefixes (un- / in- / dis- / im-)','Other prefixes (re- / pre- / mis- / over-)','Noun-forming suffixes (-tion / -ment / -ness)','Adjective suffixes (-able / -ful / -less)','Adverb suffix (-ly)','Verb suffixes (-ize / -ify)','Compound nouns','Compound adjectives','Stress in word forms'] },
    { cat: 'Pronouns', topics: ['Personal pronouns (subject / object)','Possessive pronouns and adjectives','Reflexive pronouns','Reciprocal (each other / one another)','Indefinite pronouns (someone / anything)','Pronoun reference & agreement','One / ones'] },
    { cat: 'Negation', topics: ['Negative sentences','Negative prefixes','Negative adverbs (hardly / scarcely / barely)','Double negatives','No vs not','Neither / nor / either'] },
    { cat: 'Discourse markers', topics: ['Actually / in fact','Anyway / by the way','Frankly / honestly','Well / right / OK','To be honest','I mean / you know','Discourse markers in formal writing'] },
    { cat: 'Politeness & hedging', topics: ['Hedging language (might / could / perhaps)','Polite requests with would / could','Softening with would rather / would prefer','Apologies (I\'m sorry to / I\'m afraid)','Mitigation (a bit / kind of / sort of)','Diplomatic language'] },
    { cat: 'Sentence types & word order', topics: ['Simple / compound / complex sentences','Subject-verb agreement','Word order in English','Fronting & emphasis','Inversion in formal English','Sentence fragments','Run-on sentences'] },
    { cat: 'Punctuation', topics: ['Commas','Apostrophes (possession / contractions)','Capitalisation','Colons & semicolons','Quotation marks','Hyphens & dashes'] },
    { cat: 'Comparatives — advanced', topics: ['Less / fewer','The more ... the more','Twice / three times as much','Slightly / much / far in comparisons','So / such for emphasis','Like vs as'] },
    { cat: 'Tense in academic writing', topics: ['Present simple in academic writing','Past simple for cited research','Present perfect for ongoing research','Hedging verbs (suggest / seem / appear)','Passive in academic writing','Avoiding personal pronouns'] },
  ],
  vocabulary: [
    { cat: 'Family — immediate', topics: ['Immediate family members','Family roles','Sibling relationships','Parents & parenting','Family routines'] },
    { cat: 'Family — relationships', topics: ['Marriage & weddings','Divorce & separation','Romantic relationships','Friendship','Generations','Long-term relationships'] },
    { cat: 'Daily routine', topics: ['Morning routine','Workday routine','Evening routine','Weekend activities','Time management','Chores at home'] },
    { cat: 'Personality — positive', topics: ['Friendly traits','Reliable & trustworthy','Hardworking & ambitious','Creative & innovative','Confident & assertive','Patient & understanding','Generous & kind'] },
    { cat: 'Personality — negative', topics: ['Selfish & rude','Lazy & unmotivated','Stubborn & inflexible','Insecure & anxious','Aggressive & impatient','Dishonest & deceitful','Arrogant & boastful'] },
    { cat: 'Emotions & feelings', topics: ['Happy emotions','Sad emotions','Angry emotions','Fearful emotions','Surprised emotions','Disgusted emotions','Mixed emotions','Mood swings','Stress & burnout'] },
    { cat: 'Appearance — body', topics: ['Face & features','Hair styles & colours','Body shape & height','Skin & complexion','Eyes & gaze','Voice & speech'] },
    { cat: 'Clothing & fashion', topics: ['Casual clothing','Formal clothing','Footwear','Accessories & jewellery','Materials & fabrics','Patterns & colours','Fashion trends','Sustainable fashion'] },
    { cat: 'Make-up & grooming', topics: ['Make-up products','Hair styling','Skincare','Personal hygiene'] },
    { cat: 'House — types', topics: ['Types of houses','Apartment & flat','Castle & mansion','Tiny home & alternatives','Caravans & mobile homes'] },
    { cat: 'House — rooms & areas', topics: ['Living room','Bedroom','Kitchen','Bathroom','Garage & garden','Attic & basement','Hallway & corridor'] },
    { cat: 'House — furniture & appliances', topics: ['Living room furniture','Bedroom furniture','Kitchen appliances','Bathroom fixtures','Outdoor furniture','Smart home devices'] },
    { cat: 'Renting & buying', topics: ['Renting an apartment','Mortgage & buying','Real estate agents','Moving house','House problems & repairs'] },
    { cat: 'Travel — types', topics: ['Beach holiday','City break','Cultural tourism','Adventure travel','Backpacking','Cruise vacations','Eco-tourism','Solo travel'] },
    { cat: 'Travel — transport', topics: ['Cars & driving','Public transport','Trains & railways','Planes & flying','Ships & cruises','Bicycles & e-scooters','Traffic & congestion','Road signs & rules'] },
    { cat: 'At the airport', topics: ['Check-in & boarding','Security & customs','Lost luggage','Flight delays & cancellations','Airport facilities','Immigration & passports'] },
    { cat: 'Hotel & accommodation', topics: ['Booking a hotel','Hotel rooms & features','Hotel staff','Hotel complaints','Airbnb & hostels','Camping & glamping'] },
    { cat: 'Sightseeing', topics: ['Tourist attractions','Museums & galleries','Itineraries & sightseeing','Souvenirs & gifts','Tour guides','Famous landmarks'] },
    { cat: 'Asking for directions', topics: ['Directions in the city','Compass directions','Maps & GPS','Pedestrian areas'] },
    { cat: 'Food — produce', topics: ['Fruits','Vegetables','Meat','Fish & seafood','Dairy products','Grains & cereals','Bakery items','Spices & herbs','Sweets & desserts'] },
    { cat: 'Cooking', topics: ['Cooking methods (fry / boil / bake)','Kitchen utensils','Recipes & ingredients','Cooking verbs','Meal preparation','Kitchen mishaps'] },
    { cat: 'Restaurants', topics: ['Types of restaurants','Ordering food','Paying & tipping','Restaurant complaints','Restaurant reviews','Fast food vs fine dining'] },
    { cat: 'Drinks', topics: ['Hot drinks (coffee / tea)','Soft drinks','Cocktails & spirits','Wine & beer','Coffee shop vocabulary'] },
    { cat: 'Diet & nutrition', topics: ['Diets (vegan / vegetarian / keto)','Healthy eating','Junk food','Allergies & intolerances','Counting calories','Food labels'] },
    { cat: 'Body — anatomy', topics: ['External body parts','Internal organs','Muscles & bones','The senses','Hands & feet','Head & face anatomy'] },
    { cat: 'Health — illness', topics: ['Common illnesses','Symptoms','Mental health','Chronic diseases','Pandemics & infections','Cancer & serious illness','First aid','Aging health'] },
    { cat: 'Health — care', topics: ['At the doctor\'s','At the hospital','Medicines & prescriptions','Alternative medicine','Health insurance','Surgery & operations'] },
    { cat: 'Fitness', topics: ['Types of exercise','Gym & equipment','Yoga & meditation','Running & cycling','Sports for fitness','Personal trainers'] },
    { cat: 'Education — school', topics: ['School subjects','School building & rooms','Teachers & staff','Student life','Discipline & rules','Bullying & wellbeing'] },
    { cat: 'Education — higher', topics: ['University life','Student housing','Studying & revision','Plagiarism & cheating','Online learning','Adult education','Scholarships & funding'] },
    { cat: 'Exams & assessment', topics: ['Types of exams','Exam preparation','Grades & marking','Exam stress','IELTS / TOEFL preparation'] },
    { cat: 'Foreign languages', topics: ['Learning a language','Multilingualism','Translation','Language exchange','Common learner errors'] },
    { cat: 'Work — jobs', topics: ['Common professions','Trades & manual jobs','Office jobs','Healthcare workers','Tech & IT jobs','Creative jobs','Self-employed','Public service jobs'] },
    { cat: 'Work — workplace', topics: ['Office equipment','Meetings & presentations','Colleagues & relationships','Working hours & overtime','Remote work','Career progression'] },
    { cat: 'Work — career', topics: ['Job interviews','CV & resume','Salary & promotion','Workplace conflicts','Networking','Workplace ethics'] },
    { cat: 'Business English', topics: ['Companies & organisations','Marketing & sales','International trade','Customer service','Negotiations','Startups & entrepreneurship','Mergers & acquisitions'] },
    { cat: 'Money — finance', topics: ['Currency & exchange','Banking','Credit cards & debit','Loans & mortgages','Cryptocurrency','Bills & taxes'] },
    { cat: 'Saving & spending', topics: ['Saving habits','Budgeting','Investments & shares','Pensions','Frugal living','Debt & overspending'] },
    { cat: 'Shopping', topics: ['Shop types','Shopping online','Bargains & sales','Returns & refunds','Brands & marketing','Black Friday & sales events','Subscriptions','Consumerism'] },
    { cat: 'Technology — basics', topics: ['Computers & laptops','Mobile phones & apps','The internet','Email & messaging','Social media','Apps & software','Wi-Fi & connectivity'] },
    { cat: 'Technology — society', topics: ['Cybersecurity','Privacy & data','Online dating','Streaming services','Influencers & content creators','Digital wellbeing'] },
    { cat: 'Technology — future', topics: ['Artificial intelligence','Robotics','Virtual reality','3D printing','Smart homes','Self-driving cars','Quantum computing'] },
    { cat: 'Environment', topics: ['Climate change','Pollution','Renewable energy','Recycling & waste','Endangered species','Deforestation','Sustainability','Natural disasters'] },
    { cat: 'Politics & government', topics: ['Government & politics','Elections & voting','International relations','Human rights','Activism & protests','Political parties'] },
    { cat: 'Crime & justice', topics: ['Types of crimes','Police & investigation','Courts & trials','Punishment & prisons','Cybercrime','White-collar crime','Crime prevention'] },
    { cat: 'Media & journalism', topics: ['Newspapers & magazines','TV & radio','Fake news & disinformation','Journalism ethics','Social media news'] },
    { cat: 'Globalisation', topics: ['Global economy','Migration & immigration','Cultural diversity','Tourism impact'] },
    { cat: 'Visual arts', topics: ['Painting & drawing','Sculpture','Photography','Architecture','Modern art','Street art & graffiti'] },
    { cat: 'Performing arts', topics: ['Theatre','Dance','Concerts & festivals','Cinema & films','Stand-up comedy','Opera & ballet'] },
    { cat: 'Literature', topics: ['Genres of fiction','Poetry','Famous authors','Reading habits','Book reviews'] },
    { cat: 'Music', topics: ['Music genres','Musical instruments','Singing & vocals','Concerts & festivals','Music industry','Famous musicians'] },
    { cat: 'Sport — types', topics: ['Football & basketball','Tennis & golf','Boxing & martial arts','Water sports','Winter sports','Extreme sports','Olympic sports','Esports'] },
    { cat: 'Sport — equipment & venues', topics: ['Sports equipment','Stadiums & arenas','Sportswear','Coaches & referees','Fans & supporters'] },
    { cat: 'Hobbies & free time', topics: ['Indoor hobbies','Outdoor hobbies','Collecting','Crafts & DIY','Gardening','Volunteering','Board games & puzzles'] },
    { cat: 'Animals & wildlife', topics: ['Wild animals','Farm animals','Pets','Birds','Insects','Sea creatures','Endangered species','Animal behaviour'] },
    { cat: 'Geography', topics: ['Continents & countries','Cities & towns','Mountains & valleys','Oceans & seas','Rivers & lakes','Forests & jungles','Deserts','Polar regions'] },
    { cat: 'Weather', topics: ['Weather conditions','Seasons','Climate types','Extreme weather','Weather forecasting','Weather idioms'] },
    { cat: 'Time & calendar', topics: ['Days, months, seasons','Telling the time','Time idioms','Stages of life','Time at work'] },
    { cat: 'Festivals & celebrations', topics: ['Christmas','Easter','Birthdays','Cultural festivals (Holi / Diwali / Ramadan)','Wedding traditions','New Year celebrations'] },
    { cat: 'Idioms — body & colours', topics: ['Idioms with body parts','Idioms with colours','Idioms with hands','Idioms with eyes','Idioms with hair','Idioms with feet'] },
    { cat: 'Idioms — animals & food', topics: ['Idioms with animals','Idioms with food','Idioms with cats / dogs','Idioms with fish','Idioms with eggs'] },
    { cat: 'Idioms — abstract', topics: ['Idioms with money','Idioms with time','Idioms with weather','Idioms with light & dark','Business idioms','Travel idioms'] },
    { cat: 'Phrasal verbs — common', topics: ['Phrasal verbs with up','Phrasal verbs with out','Phrasal verbs with off','Phrasal verbs with on','Phrasal verbs with in','Phrasal verbs with down','Phrasal verbs with away'] },
    { cat: 'Phrasal verbs — themed', topics: ['Travel phrasal verbs','Business phrasal verbs','Relationship phrasal verbs','Health phrasal verbs','Daily routine phrasal verbs','Conversation phrasal verbs'] },
    { cat: 'Collocations', topics: ['Verb + noun collocations','Adjective + noun collocations','Strong collocations (heavy rain)','Adverb + adjective (highly successful)','Common verb collocations','Academic collocations','Business collocations'] },
    { cat: 'Confusing & related words', topics: ['Affect / effect','Lose / loose','Their / there / they\'re','Make / do','Borrow / lend','Bring / take','Say / tell','Other commonly confused pairs'] },
    { cat: 'Synonyms & antonyms', topics: ['Common synonym pairs','Common antonym pairs','Word levels (formal / informal)','Subtle differences in meaning'] },
    { cat: 'False friends', topics: ['Russian-English false friends','Uzbek-English false friends','International false friends'] },
  ],
};
