-- ============================================================================
-- daily_health_snapshot(): stop counting re-sends as submissions.
-- ----------------------------------------------------------------------------
-- Applied 2026-08-21. The 08:00 report claimed "not delivered: -314 (-23%)",
-- which is not a number that can exist: it counted every distinct key in
-- telegram_send_log as a delivered submission, and a re-send from the Resend
-- Reports panel writes its own key ('resend-<uuid>'). 279 of them on 20 Aug
-- pushed the delivered count above the number of reports taken.
--
-- Delivered submissions are now counted ONLY from keys shaped like a results
-- row id — the same filter `sent_ids` already used for the missing-report list
-- — and the re-send count is reported separately. What remained after the fix
-- was a gap of -34: last night's stragglers delivered by the 5-minute sweep
-- after midnight, which is the boundary working as designed, so the digest
-- says "every report delivered" instead of printing a negative percentage.
-- ============================================================================
-- (Function body applied via SQL; see the deployed definition — this file
--  records WHY, and the change is a two-line filter in the tg / tg_week CTEs.)

-- ── Follow-up the same morning ──────────────────────────────────────────────
-- Davirbek asked the right question: would a report HE re-sent by hand now be
-- reported as a failure? It would have. A re-send is keyed
-- 'resend-<row id>-<epoch>' (the timestamp so a second re-send is not deduped
-- against the first), and the missing-report list only matched bare row ids —
-- so a report rescued through the panel still counted as never delivered.
--
--   tg_result_id(idem_key)  unwraps that key back to the row it rescued.
--
-- With every send resolving to a row id, the day's figure changed from
-- "messages sent" to "reports delivered": of the reports taken today, how many
-- reached Telegram. That cannot exceed the day's total, so the negative
-- percentages are gone by construction rather than by special-casing.
--
--   tg_delivery_baseline(days, offset)  the 7-day comparison, counting ONLY
--   days whose sends carried the report id. Sends became id-keyed on 20 Aug
--   2026: 13-18 Aug read as "5% delivered" because there was nothing to match,
--   not because anything was lost. Days under half are treated as unmeasurable
--   and the digest says "baseline building" until three exist.
